# load packages, installing if needed ----
packages = c(
  # general data science
  'tidyverse','stringr','tools','lubridate',
  # spatial
  'sf','leaflet','htmltools', 'bhaskarvk/leaflet.extras','rmapshaper','geojsonio','ncdf4','raster',
  # time-series plot
  'xts','dygraphs','hrbrmstr/streamgraph','wch/webshot',
  # shiny
  'shiny','shinyWidgets','shinydashboard')
# webshot::install_phantomjs()
for (pkg in packages){ # pkg= packages[1] # pkg = 'r-spatial/mapview@develop' # pkg='ropensci/plotly' # pkg='rmapshaper'
  github_pkg = grepl('/', pkg)
  p = ifelse(github_pkg, sub('([-0-9A-Za-z]*)/([-0-9A-Za-z]*)@?([-0-9A-Za-z]*)', '\\2', pkg), pkg)
  if (!require(p, character.only=T)){
    if (github_pkg){
      if (!require(devtools)) install.packages('devtools')
      devtools::install_github(pkg)
    } else {
      install.packages(p)
    }
    library(p, character.only=T)
  }
}
# override namespace with preferred function calls
select    = dplyr::select
addLegend = leaflet::addLegend

options(shiny.sanitize.errors = F)

dir_wd = 'bio2'
if (basename(getwd())!=dir_wd) setwd(dir_wd)

dir_root = switch(
  Sys.info()[['sysname']],
  'Darwin'  = '/Volumes/Best HD/mbon_data_big', # BB's Mac
  'Windows' = 'P:',                             # constance.bren.ucsb.edu
  'Linux'   = '/mbon/data_big')                 # mbon.marine.usf.edu

eez_metrics_csv = 'data/_eez_obis_metrics.csv' # generated by sdg14/technical/obis-eez-metric.R
eez_taxa_csv    = 'data/_eez_obis_taxa.csv'  # generated by sdg14/technical/obis-eez-metric.R
eez_s005_shp    = '../info-gl/data/eez_s005.shp'
eez_s005005_shp = '../info-gl/data/eez_s005005.shp'

# process data
eez_metrics = read_csv(eez_metrics_csv)
eez_taxa    = read_csv(eez_taxa_csv)

eez_sf = read_sf(eez_s005005_shp) %>%
  filter(Pol_type=='200NM') %>%
  left_join(
    eez_metrics,
    by = c('Territory1'='eez_territory1')) # plot(eez_sf['n_obs'])

eez_territories = eez_sf %>% filter(!is.na(n_obs)) %>% .$Territory1

taxa_ranks = c('taxonomicgroup', 'kingdom', 'phylum', 'class', 'order', 'family', 'genus', 'species')