# load packages
library(tidyverse)
library(rlang)
library(purrr)
library(stringr)
library(lubridate)
library(rmarkdown)
library(leaflet)
library(sf)
library(shiny)
library(shinydashboard)
library(shinyWidgets)
library(htmltools)
library(xml2)
library(RColorBrewer)
library(dygraphs)
library(xts)
library(brew)
library(streamgraph) # devtools::install_github('hrbrmstr/streamgraph')
addLegend = leaflet::addLegend

# debug ----
# https://shiny.rstudio.com/reference/shiny/latest/shiny-options.html
options(
  shiny.sanitize.errors = F, shiny.autoreload=F,
  shiny.fullstacktrace=F, shiny.stacktraceoffset=T,
  shiny.trace=F, shiny.testmode=F, shiny.minified=T,
  shiny.deprecation.messages=T,
  shiny.reactlog=F)

msg = function(txt, debug=F){
  if (debug)
    cat(sprintf('%s ~ %s\n', txt, Sys.time()), file=stderr())
}

# paths ----
#dir_wd = 'explorer'
#if (basename(getwd())!=dir_wd) setwd(dir_wd)

dir_local = switch(
  Sys.info()[['sysname']],
  'Darwin'  = '/Volumes/Best HD/mbon_data_big/local', # BB's Mac
  'Windows' = 'P:',                                          # constance.bren.ucsb.edu
  'Linux'   = '/mbon-local')                 # mbon.marine.usf.edu

#pwd = getwd()
pwd = '/mbon/shiny/explorer'

#eez_s005005_shp = file.path(dir_local, 'boundaries/eez_s005005.shp')
eez_s005005_shp = file.path(pwd, 'data/eez_s005005.shp')
# generated by sdg14/technical/obis-eez-metric.R
#eez_metrics_csv = file.path(dir_local, 'obis/_eez_obis_metrics.csv') 
eez_metrics_csv = file.path(pwd, 'data/_eez_obis_metrics.csv')
#eez_taxa_csv    = file.path(dir_local, 'obis/_eez_obis_taxa.csv')

# obis ----
eez_metrics = read_csv(eez_metrics_csv) %>%
  left_join(
    tribble(
    ~eez_territory1, ~n_obs_1, ~n_spp_1, ~idx_obis_wdpa_tmp,
            'Russia',   462225,     5328,                0.5,
            'Canada',  4349491,    10997,                0.5,
            'Alaska',   987121,     5196,                0.5),
    by='eez_territory1') %>%
  mutate(
    n_obs         = ifelse(is.na(n_obs_1), n_obs, n_obs_1),
    n_spp         = ifelse(is.na(n_spp_1), n_spp, n_spp_1),
    idx_obis_wdpa = ifelse(is.na(idx_obis_wdpa_tmp), idx_obis_wdpa, idx_obis_wdpa_tmp)) %>%
  select(eez_territory1, eez_pol_type, n_obs, n_spp, idx_obis_wdpa)

# eez_taxa = read_csv(eez_taxa_csv) %>%
#   group_by(taxonomicgroup, kingdom, phylum, class, order, family, genus, species) %>%
#   summarise(n_tmp=n())
# taxa_ranks  = c('taxonomicgroup', 'kingdom', 'phylum', 'class', 'order', 'family', 'genus', 'species')

# eez ----
eez_sf = read_sf(eez_s005005_shp)  %>%
  filter(Pol_type=='200NM') %>% # not 'Disputed','Joint regime'
  mutate(
    n_sov = n(),
    sov_ter = ifelse(
      Sovereign1 == Territory1,
      Sovereign1,
      sprintf('%s - %s', Sovereign1, Territory1))) %>% 
  ungroup() %>%
  left_join(
    eez_metrics,
    by = c('Territory1'='eez_territory1')) %>%
  arrange(sov_ter)

eez_labels = sprintf(
  '<strong>%s</strong>',
  eez_sf$sov_ter) %>% 
  lapply(HTML)

eez_territories = eez_sf %>% filter(!is.na(n_obs)) %>% .$Territory1

# env layers ----
# get dates from WMS layer time list
#wms_xml = file.path(dir_local, 'shiny_tmp/wms.xml')
wms_xml = file.path(pwd, 'data/wms.xml')
wms_url = 'http://mbon.marine.usf.edu:8080/geoserver/ows?service=wms&version=1.3.0&request=GetCapabilities'
if (!file.exists(wms_xml)){
  download.file(wms_url, wms_xml)
}
xml = read_xml(wms_xml)

get_wms_dates = function(xml, lyr){
  # lyr = 'gl_sst_curr_09km_mo'
  xpath = sprintf("//d1:Layer/d1:Layer[contains(d1:Name,'satellite:%s')]/d1:Dimension", lyr)
  xml %>%
    xml_find_first(xpath) %>%
    xml_text() %>%
    str_split(',') %>%
    .[[1]] %>%
    str_sub(1,10) %>%
    sort(decreasing=T) %>%
    as.Date()
}

env_vars = list(
  chl     = list(
    dy_title   = 'Chlorophyll', 
    dy_lab     = 'Chl <i>a</i> (log(mg/m<sup>3</sup>))',
    legend     = 'Chl <i>a</i> (mg/m<sup>3</sup>)',
    values     = seq(-6.91, 4.61, length.out = 7),
    pal        = colorNumeric('Greens', seq(-6.91, 4.61, length.out = 7), na.color='transparent'),
    transform  = function(x){ round(exp(x),2) },
    curr_lyr   = 'gl_chl_curr_09km_mo',
    curr_dates = get_wms_dates(xml, 'gl_chl_curr_09km_mo'),
    #curr_eez   = read_csv(sprintf('%s/raster-extract/eez_%s.csv', dir_local, 'gl_chl_curr_09km_mo'))),
    curr_eez   = read_csv(file.path(pwd, 'data/eez_gl_chl_curr_09km_mo.csv'))),
  seascape=list(
    legend     = 'Class',
    values     = 1:14,
    pal        = colorFactor(colorRampPalette(brewer.pal(11,'Spectral'))(14), 1:14, na.color='transparent'),
    transform = function(x){ x },
    curr_lyr   = 'gl_sea_curr_09km_mo',
    curr_dates = get_wms_dates(xml, 'gl_sea_curr_09km_mo'),
    #curr_eez   = read_csv(sprintf('%s/raster-extract/eez_%s.csv', dir_local, 'gl_sea_curr_09km_mo'))),
    curr_eez   = read_csv(file.path(pwd, 'data/eez_gl_sea_curr_09km_mo.csv'))),
  sst     = list(
    dy_title   = 'Sea Surface Temperature', 
    dy_lab     = 'SST (°C)',
    legend     = 'SST (°C)',
    values     = seq(-4, 36, length.out = 7),
    pal        = colorNumeric('Reds', seq(-4, 36, length.out = 7), na.color='transparent'),
    transform = function(x){ x },
    curr_lyr   = 'gl_sst_curr_09km_mo',
    curr_dates = get_wms_dates(xml, 'gl_sst_curr_09km_mo'),
    #curr_eez   = read_csv(sprintf('%s/raster-extract/eez_%s.csv', dir_local, 'gl_sst_curr_09km_mo'))))
    curr_eez   = read_csv(file.path(pwd, 'data/eez_gl_sst_curr_09km_mo.csv'))))

# defaults
bio_var = 'n_spp'
env_var = 'chl'
dates = env_vars[[env_var]][['curr_dates']] %>% sort()

enableBookmarking("server")

# TODO: add modal for index metric
# TODO: get taxa filter functioning

# TODO: other env w/ clim: chl, sst 9km
# [Using the ImageMosaic extension — GeoServer 2.13.x User Manual](http://docs.geoserver.org/latest/en/user/data/raster/imagemosaic/tutorial.html)

# TODO: WMS legend
# http://mbon.marine.usf.edu:8080/geoserver/wms?REQUEST=GetLegendGraphic&VERSION=1.3.0&FORMAT=image/png&WIDTH=20&HEIGHT=20&LAYER=satellite:sst_monthly_mean_27km
# https://github.com/bhaskarvk/leaflet.extras/blob/master/inst/examples/wmsLegend.R

# TODO: optimize caching params
# http://docs.geoserver.org/stable/en/user/geowebcache/webadmin/defaults.html

# TODO: dynamic GeoServer layer creation/deletion
# [CRAN - Package geosapi](https://cran.r-project.org/web/packages/geosapi/index.html)

# TODO: update password for postgis docker, geoserver admin

# TODO: vector tile EEZ
# [Vector tiles tutorial — GeoServer 2.13.x User Manual](http://docs.geoserver.org/latest/en/user/extensions/vectortiles/tutorial.html)