# load packages
library(tidyverse)
library(rlang)
library(purrr)
library(stringr)
library(lubridate)
library(rmarkdown)
library(leaflet)
library(sf)
library(shiny)
library(shinydashboard)
library(shinyWidgets)
library(htmltools)
library(xml2)
library(RColorBrewer)
library(dygraphs)
library(xts)
library(brew)
library(glue)
library(rerddap)  # install.packages("rerddap")
library(streamgraph) # devtools::install_github('hrbrmstr/streamgraph')
addLegend = leaflet::addLegend

# debug ----
# https://shiny.rstudio.com/reference/shiny/latest/shiny-options.html
options(
  shiny.sanitize.errors = F, shiny.autoreload=F,
  shiny.fullstacktrace=F, shiny.stacktraceoffset=T,
  shiny.trace=F, shiny.testmode=F, shiny.minified=T,
  shiny.deprecation.messages=T,
  shiny.reactlog=F)

# functions ----

msg = function(txt, debug=T){
  if (debug)
    cat(sprintf('%s ~ %s\n', txt, Sys.time()), file=stderr())
}

# paths ----
#dir_wd = 'explorer'
#if (basename(getwd())!=dir_wd) setwd(dir_wd)

dir_local = switch(
  Sys.info()[['sysname']],
  'Darwin'  = '/Volumes/Best HD/mbon_data_big/local', # BB's Mac
  'Windows' = 'P:',                 # constance.bren.ucsb.edu
  'Linux'   = '/mbon-local')                 # mbon.marine.usf.edu

pwd = getwd()
#pwd = '/mbon/shiny/explorer'

#eez_s005005_shp = file.path(dir_local, 'boundaries/eez_s005005.shp')
eez_s005005_shp = file.path(pwd, 'data/eez_s005005.shp') #%>% 
  #st_transform(4326)
# generated by sdg14/technical/obis-eez-metric.R
#eez_metrics_csv = file.path(dir_local, 'obis/_eez_obis_metrics.csv') 
eez_metrics_csv = file.path(pwd, 'data/_eez_obis_metrics.csv')
#eez_taxa_csv    = file.path(dir_local, 'obis/_eez_obis_taxa.csv')

# obis ----
eez_metrics = read_csv(eez_metrics_csv) %>%
  left_join(
    tribble(
    ~eez_territory1, ~n_obs_1, ~n_spp_1, ~idx_obis_wdpa_tmp,
            'Russia',   462225,     5328,                0.5,
            'Canada',  4349491,    10997,                0.5,
            'Alaska',   987121,     5196,                0.5),
    by='eez_territory1') %>%
  mutate(
    n_obs         = ifelse(is.na(n_obs_1), n_obs, n_obs_1),
    n_spp         = ifelse(is.na(n_spp_1), n_spp, n_spp_1),
    idx_obis_wdpa = ifelse(is.na(idx_obis_wdpa_tmp), idx_obis_wdpa, idx_obis_wdpa_tmp)) %>%
  select(eez_territory1, eez_pol_type, n_obs, n_spp, idx_obis_wdpa)

# eez_taxa = read_csv(eez_taxa_csv) %>%
#   group_by(taxonomicgroup, kingdom, phylum, class, order, family, genus, species) %>%
#   summarise(n_tmp=n())
# taxa_ranks  = c('taxonomicgroup', 'kingdom', 'phylum', 'class', 'order', 'family', 'genus', 'species')

# eez ----
eez_sf = read_sf(eez_s005005_shp)  %>%
  filter(Pol_type=='200NM') %>% # not 'Disputed','Joint regime'
  mutate(
    n_sov = n(),
    sov_ter = ifelse(
      Sovereign1 == Territory1,
      Sovereign1,
      sprintf('%s - %s', Sovereign1, Territory1))) %>% 
  ungroup() %>%
  left_join(
    eez_metrics,
    by = c('Territory1'='eez_territory1')) %>%
  arrange(sov_ter)

eez_labels = sprintf(
  '<strong>%s</strong>',
  eez_sf$sov_ter) %>% 
  lapply(HTML)

eez_territories = eez_sf %>% filter(!is.na(n_obs)) %>% .$Territory1

# env layers ----
# get dates from WMS layer time list
#wms_xml = file.path(dir_local, 'shiny_tmp/wms.xml')
wms_xml = file.path(pwd, 'data/wms.xml')
wms_url = 'http://mbon.marine.usf.edu:8080/geoserver/ows?service=wms&version=1.3.0&request=GetCapabilities'
if (!file.exists(wms_xml)){
  download.file(wms_url, wms_xml)
}
xml = read_xml(wms_xml)

get_wms_dates = function(xml, lyr){
  # lyr = 'gl_sst_curr_09km_mo'
  xpath = sprintf("//d1:Layer/d1:Layer[contains(d1:Name,'satellite:%s')]/d1:Dimension", lyr)
  xml %>%
    xml_find_first(xpath) %>%
    xml_text() %>%
    str_split(',') %>%
    .[[1]] %>%
    str_sub(1,10) %>%
    sort(decreasing=T) %>%
    as.Date()
}

# env_vars ----

env_vars = list(
  chl     = list(
    #https://coastwatch.pfeg.noaa.gov/erddap/wms/erdMH1chlamday/request?service=WMS&version=1.3.0&request=GetMap&bbox=-89.99,-179.99,89.99,180.0&time=2019-04-16T00:00:00Z&crs=EPSG:4326&width=360&height=180&layers=erdMH1chlamday:chlorophyll&format=image/png
    #baseUrl    = "https://coastwatch.pfeg.noaa.gov/erddap/wms/erdMH1chlamday/request?",
    #layer      = "erdMH1chlamday:chlorophyll",
    erddap     = "https://coastwatch.pfeg.noaa.gov/erddap/",
    datasetid  = "erdMH1chlamday",
    variable   = "chlorophyll",
    dy_title   = 'Chlorophyll', 
    dy_lab     = 'Chl <i>a</i> (log(mg/m<sup>3</sup>))',
    legend     = 'Chl <i>a</i> (mg/m<sup>3</sup>)',
    values     = seq(0.03, 30, length.out=7),
    #pal        = colorNumeric('Greens', seq(-6.91, 4.61, length.out = 7), na.color='transparent'),
    pal        = colorNumeric(colorRampPalette(gmtColors("rainbow"))(32), seq(0.03, 30, length.out=7), na.color='transparent'),
    #previewColors(colorNumeric(colorNumeric(colorRampPalette(gmtColors("rainbow"))(32), seq(0.03, 30, length.out=7), na.color='transparent'), seq(0.03, 30, length.out=7))
    transform  = function(x){ round(exp(x),2) },
    #curr_lyr   = 'gl_chl_curr_09km_mo', # "erdMH1chla8day:chlorophyll"
    #curr_dates = get_erddap_dates("chl"), # as.Date(c("2003-01-16","2019-04-16")), # get_wms_dates(xml, 'gl_chl_curr_09km_mo'),
    #curr_eez   = read_csv(sprintf('%s/raster-extract/eez_%s.csv', dir_local, 'gl_chl_curr_09km_mo'))),
    curr_eez   = read_csv(file.path(pwd, 'data/eez_gl_chl_curr_09km_mo.csv'))),
  seascape=list(
    # https://cwcgom.aoml.noaa.gov/erddap/wms/noaa_aoml_4729_9ee6_ab54/request?service=WMS&version=1.3.0&request=GetMap&bbox=-89.99,-179.99,89.99,180.0&time=2003-01-15T12:00:00Z&crs=EPSG:4326&width=360&height=180&layers=noaa_aoml_4729_9ee6_ab54:CLASS&format=image/png
    #baseUrl    = "https://cwcgom.aoml.noaa.gov/erddap/wms/noaa_aoml_4729_9ee6_ab54/request?",
    #layer      = "noaa_aoml_4729_9ee6_ab54:CLASS",
    erddap     = "https://cwcgom.aoml.noaa.gov/erddap/",
    datasetid  = "noaa_aoml_4729_9ee6_ab54",
    variable   = "CLASS",
    legend     = 'Class',
    values     = factor(1:33),
    #pal        = colorFactor(colorRampPalette(brewer.pal(11,'Spectral'))(14), 1:14, na.color='transparent'),
    pal        = colorFactor(colorRampPalette(gmtColors("rainbow"))(33), 1:33, na.color='transparent'),
    #previewColors(colorFactor(colorRampPalette(gmtColors("rainbow"))(33), 1:33, na.color='transparent'), 1:33)
    #transform = function(x){ x },
    #curr_lyr   = 'gl_sea_curr_09km_mo', # "noaa_aoml_4729_9ee6_ab54:CLASS"
    #curr_dates = as.Date(c("2003-01-15","2018-09-15")), # get_wms_dates(xml, 'gl_sea_curr_09km_mo'),
    #curr_eez   = read_csv(sprintf('%s/raster-extract/eez_%s.csv', dir_local, 'gl_sea_curr_09km_mo'))),
    #curr_eez   = read_csv(file.path(pwd, 'data/eez_gl_sea_curr_09km_mo.csv'))),
  sst     = list(
    #https://coastwatch.pfeg.noaa.gov/erddap/wms/jplMURSST41/request?service=WMS&version=1.3.0&request=GetMap&bbox=-89.99,-179.99,89.99,180.0&time=2002-06-01T09:00:00Z&crs=EPSG:4326&width=360&height=180&layers=jplMURSST41:analysed_sst&format=image/png
    #baseUrl   = "https://coastwatch.pfeg.noaa.gov/erddap/wms/jplMURSST41mday/request?",
    #wms_url   = glue("{v$erddap}wms/{v$datasetid}/request?",
    #layer     = glue("{v$datasetid}:{layer}"),
    erddap     = "https://coastwatch.pfeg.noaa.gov/erddap/",
    datasetid  = "jplMURSST41mday",
    variable   = "sst",
    dy_title   = 'Sea Surface Temperature', 
    dy_lab     = 'SST (°C)',
    legend     = 'SST (°C)',
    values     = seq(0, 32, length.out = 7),
    #pal        = colorNumeric('Reds', seq(-4, 36, length.out = 7), na.color='transparent'),
    pal        = colorNumeric(colorRampPalette(gmtColors("rainbow"))(32), 0:32, na.color='transparent'),
    #previewColors(colorNumeric(colorRampPalette(gmtColors("rainbow"))(32), 0:32, na.color='transparent'), 1:32)
    transform = function(x){ x },
    #curr_lyr   = 'gl_sst_curr_09km_mo', # "jplMURSST41mday:sst"
    #curr_dates = get_wms_dates(xml, 'gl_sst_curr_09km_mo'),
    #curr_eez   = read_csv(sprintf('%s/raster-extract/eez_%s.csv', dir_local, 'gl_sst_curr_09km_mo'))))
    #curr_eez   = read_csv(file.path(pwd, 'data/eez_gl_sst_curr_09km_mo.csv'))))

erddap_range <- function(var){ # var="chl"
  v <- env_vars[[var]]
  
  dataset <- rerddap::info(v$datasetid, v$erddap)
  
  dates <- dataset$alldata$time %>% 
    filter(attribute_name=="actual_range") %>% 
    pull(value) %>% 
    str_split(", ", simplify = T) %>% 
    as.numeric() %>% 
    as.POSIXct(origin = "1970-01-01", tz = "GMT")
  
  dataset$alldata[[v$variable]] %>% 
    filter(attribute_name %in% c("colorBarMinimum","colorBarMaximum")) %>% 
    mutate(value = as.double(value)) %>% 
    select(-row_type, -variable_name, -data_type) %>% 
    spread(attribute_name, value) %>% 
    mutate(var = !!var) %>% 
    select(var, value_min=colorBarMinimum, value_max=colorBarMaximum) %>% 
    mutate(
      date_min = dates[1],
      date_max = dates[2])
  #pull(value) %>% as.double() %>% sort() # 32  
}
get_erddap_dates <- function(var){ # var="chl"
  v <- env_vars[[var]]
  
  dataset <- rerddap::info(v$datasetid, v$erddap)
  
  dataset$alldata$time %>% 
    filter(attribute_name=="actual_range") %>% 
    pull(value) %>% 
    str_split(", ", simplify = T) %>% 
    as.numeric() %>% 
    as.POSIXct(origin = "1970-01-01", tz = "GMT")
}

update_erddap_dates <- function(var){
  env_vars[[var]]$date_range = get_erddap_dates(var)
}
walk(names(env_vars), update_erddap_dates)

value_range = c(0.03, 30),
date_range = c(0.03, 30),


#map_df(names(env_vars), erddap_range)
#        var value_min value_max            date_min            date_max
# 1      chl      0.03        30 2003-01-16 00:00:00 2019-04-16 00:00:00
# 3      sst      0.00        32 2002-06-16 00:00:00 2019-04-16 00:00:00
# 2 seascape      1.00        33 2003-01-15 12:00:00 2018-09-15 12:00:00

#dataset$alldata$sst %>% filter(attribute_name == "colorBarMaximum") %>% pull(value) %>% as.double() # 0

# defaults
bio_var = 'n_spp'
env_var = 'chl'
#dates = env_vars[[env_var]][['curr_dates']] %>% sort()

enableBookmarking("server")

# TODO: add modal for index metric
# TODO: get taxa filter functioning

# TODO: other env w/ clim: chl, sst 9km
# [Using the ImageMosaic extension — GeoServer 2.13.x User Manual](http://docs.geoserver.org/latest/en/user/data/raster/imagemosaic/tutorial.html)

# TODO: WMS legend
# http://mbon.marine.usf.edu:8080/geoserver/wms?REQUEST=GetLegendGraphic&VERSION=1.3.0&FORMAT=image/png&WIDTH=20&HEIGHT=20&LAYER=satellite:sst_monthly_mean_27km
# https://github.com/bhaskarvk/leaflet.extras/blob/master/inst/examples/wmsLegend.R

# TODO: optimize caching params
# http://docs.geoserver.org/stable/en/user/geowebcache/webadmin/defaults.html

# TODO: dynamic GeoServer layer creation/deletion
# [CRAN - Package geosapi](https://cran.r-project.org/web/packages/geosapi/index.html)

# TODO: update password for postgis docker, geoserver admin

# TODO: vector tile EEZ
# [Vector tiles tutorial — GeoServer 2.13.x User Manual](http://docs.geoserver.org/latest/en/user/extensions/vectortiles/tutorial.html)


gmtColors <- function(pal.name="rainbow"){
  #function 'gmtColors' to call color levels.
  #palette name `pal.name` is one of the following:
  #"cool", "copper", "gebco", "globe", "gray",
  #"haxby", "hot", "jet", "no_green", "ocean",
  #"polar", "rainbow", "red2green", "relief", "sealand",
  #"seis", "split", "topo", "wysiwyg"
  # [GMT standard color palettes | R-bloggers](https://www.r-bloggers.com/gmt-standard-color-palettes/)
  tmp <- structure(list(
    cool = c(
      "#00FFFF", "#0DF2FF", "#19E6FF", "#26D9FF", "#33CCFF", "#3FBFFF", "#4CB3FF", "#59A6FF", "#6699FF", "#738CFF", 
      "#7F7FFF", "#8C73FF", "#9966FF", "#A659FF", "#B24DFF", "#BF3FFF", "#CC33FF", "#D926FF", "#E619FF", "#F20DFF"), 
    copper = c(
      "#000000", "#100906", "#1F130D", "#301E13", "#40281A", "#50321F", "#603C26", "#70462D", "#805033", "#905A3A", 
      "#A06440", "#B06E46", "#C0784D", "#D08253", "#E08C5A", "#F09660", "#FFA066", "#FFAA6D", "#FFB473", "#FFBE7A"), 
    gebco = c(
      "#00F0FF", "#00F0FF", "#00F0FF", "#23FFFF", "#23FFFF", "#23FFFF", "#5AFFFF", "#5AFFFF", "#5AFFFF", "#8CFFE6", 
      "#8CFFE6", "#8CFFE6", "#A5FFD7", "#A5FFD7", "#A5FFD7", "#C3FFD7", "#C3FFD7", "#C3FFD7", "#D2FFD7", "#E6FFF0"), 
    globe = c(
      "#9900FF", "#9900FF", "#7722FF", "#5544FF", "#3366FF", "#1188FF", "#1BA4FF", "#51BAFF", "#86D0FF", "#BCE6FF", 
      "#336600", "#F3CA89", "#D9A627", "#A49019", "#9F7B0D", "#996600", "#B27676", "#C2B0B0", "#E5E5E5", "#FFFFFF"),
    gray = c(
      "#000000", "#0D0D0D", "#191919", "#262626", "#333333", "#3F3F3F", "#4C4C4C", "#595959", "#666666", "#737373", 
      "#7F7F7F", "#8C8C8C", "#999999", "#A6A6A6", "#B2B2B2", "#BFBFBF", "#CCCCCC", "#D9D9D9", "#E6E6E6", "#F2F2F2"),
    haxby = c(
      "#090079", "#280096", "#0009C8", "#0019D4", "#1A66F0", "#19AFFF", "#32BEFF", "#61E1F0", "#6AECE1", "#8AECAE", 
      "#CDFFA2", "#DFF68D", "#F8D768", "#FFBD57", "#F4754B", "#FF5A5A", "#FF7C7C", "#F6B3AE", "#FFC4C4", "#FFECEC"), 
    hot = c(
      "#000000", "#220000", "#440000", "#660000","#880000", "#AA0000", "#CC0000", "#EE0000", "#FF1100", "#FF3300", 
      "#FF5500", "#FF7700", "#FF9900", "#FFBB00", "#FFDD00", "#FFFF00", "#FFFF33", "#FFFF66", "#FFFF99", "#FFFFCC"), 
    jet = c(
      "#00007F", "#0000B2", "#0000E5", "#0019FF", "#004DFF", "#007FFF", "#00B2FF", "#00E5FF", "#FFFFF2", "#FFFFD9", 
      "#FFFFBF", "#FFFFA5", "#FFFF8C", "#FFE500", "#FFB300", "#FF7F00", "#FF4C00", "#FF1900", "#E50000", "#B20000"), 
    no_green = c(
      "#1F60FF", "#1F60FF", "#1F9FFF", "#1FBFFF", "#00CFFF", "#2AFFFF", "#2AFFFF", "#55FFFF", "#7FFFFF", "#AAFFFF", 
      "#FFFF54", "#FFFF54", "#FFF000", "#FFBF00", "#FFA800", "#FF8A00", "#FF8A00", "#FF7000", "#FF4D00", "#FF0000"), 
    ocean = c(
      "#000000", "#000209", "#000413", "#00061E", "#000728", "#000932", "#002650", "#00426E", "#005E8C", "#007AAA", 
      "#0096C8", "#22A9C2", "#45BCBB", "#67CFB5", "#8AE2AE", "#ACF6A8", "#BCF8B9", "#CBF9CA", "#DBFBDC", "#EBFDED"), 
    polar = c(
      "#0000FF", "#1919FF", "#3333FF", "#4C4CFF", "#6666FF", "#7F7FFF", "#9999FF", "#B2B2FF", "#CCCCFF", "#E6E6FF", 
      "#FFFFFF", "#FFE5E5", "#FFCCCC", "#FFB2B2", "#FF9999", "#FF7F7F", "#FF6666", "#FF4C4C", "#FF3333", "#FF1A1A"), 
    rainbow = c(
      "#FF00FF", "#BF00FF", "#7F00FF", "#3F00FF", "#0000FF", "#003FFF", "#007FFF", "#00BFFF", "#00FFFF", "#00FFBF", 
      "#00FF7F", "#00FF3F", "#00FF00", "#3FFF00", "#7FFF00", "#BFFF00", "#FFFF00", "#FFBF00", "#FF7F00", "#FF3F00"),
    red2green = c(
      "#FF0000", "#FF1919", "#FF3333", "#FF4C4C", "#FF6666", "#FF7F7F", "#FF9999", "#FFB2B2", "#FFCCCC", "#FFE6E6", 
      "#FFFFFF", "#E5FFE5", "#CCFFCC", "#B2FFB2", "#99FF99", "#7FFF7F", "#66FF66", "#4CFF4C", "#33FF33", "#1AFF1A"), 
    relief = c(
      "#000000", "#000413", "#000728", "#002650", "#005E8C", "#0096C8", "#45BCBB", "#8AE2AE", "#BCF8B9", "#DBFBDC", 
      "#467832", "#887438", "#B19D48", "#DBC758", "#FAE769", "#FAEB7E", "#FCED93", "#FCF1A7", "#FCF6C1", "#FDFAE0"), 
    sealand = c(
      "#8C66FF", "#6A66FF", "#6684FF", "#66A7FF", "#66CAFF", "#66ECFF", "#66FFF0", "#66FFCE", "#66FFAB", "#66FF88", 
      "#66FF66", "#88FF66", "#ABFF66", "#CEFF66", "#FFEEA6", "#FFD3A6", "#FFB8A6", "#FFAAB0", "#FFB5CB", "#FFC0E1"), 
    seis = c(
      "#AA0000", "#D00000", "#F70000", "#FF1D00", "#FF4400", "#FF6A00", "#FF9000", "#FFB700", "#FFDD00", "#FFFF00", 
      "#FFFF00", "#FFFF00", "#BDFF0C", "#73FF1A", "#3FFA36", "#16F45A", "#00D08B", "#0087CD", "#0048FA", "#0024E3"), 
    split = c(
      "#7F7FFF", "#6666E6", "#4D4DCC", "#3333B3", "#1A1A99", "#00007F", "#000066", "#00004D", "#000033", "#00001A", 
      "#000000", "#1A0000", "#330000", "#4D0000", "#660000", "#7F0000", "#991A1A", "#B33333", "#CC4D4D", "#E66666"), 
    topo = c(
      "#C977D9", "#A18AE6", "#8AA2E6", "#8BD1E7", "#8AF3CF", "#85F38E", "#BDF385", "#EDE485", "#F0B086", "#DE9F8B", 
      "#74A3B3", "#99CC70", "#DCD68E", "#EDDFAD", "#F7E8CA", "#FFF9F3", "#FFF9F6", "#FFFBF9", "#FFFCFA", "#FFFEFD"), 
    wysiwyg = c(
      "#3F003F", "#3F003F", "#3F00BF", "#003FFF", "#00A0FF", "#3FBFFF", "#3FBFFF", "#40E0FF", "#3FFFBF", "#3FFF3F", 
      "#7FFF3F", "#BFFF3F", "#BFFF3F", "#FFE040", "#FFE040", "#FF6040", "#FF1F40", "#FF60C0", "#FFA0FF", "#FFA0FF")), 
    .Names = c(
      "cool", "copper", "gebco", "globe", "gray", "haxby", "hot", "jet", "no_green", "ocean", "polar", 
      "rainbow", "red2green", "relief", "sealand", "seis", "split", "topo", "wysiwyg"))
  tmp[[match(pal.name, names(tmp))]]
}